name: Use Secret for API

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Call API with secret
        run: curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://api.example.com/data
